### ISSUE TITLE
[Bug] Email verification to unlock account annoying user.

### ISSUE THREAD

**Issue by DucTran999** [DucTran999/fashion-shop#83]
**Description**
&emsp; The new feature for unlocking the user account immediately by verifying the email is annoying. Since some logic was not working correctly, the email service spammed both users in the system and others. 

**Steps to reproduce**
1. Access the login page.
2. Fill in the email and password fields. (Use an email not registered or the wrong password or both)
3. Submitting the form five times in a row.

**Actual behavior**
&emsp;  2 email is automatically sent without checking email is registered or not. 

**Expected behavior** 
&emsp; The system sends the email when the user requests.

**The impact of the bug:** 
&emsp;  If a brute force attack is conducted, the mail service will send emails out of control.

**Severity:** `Critical`

Assignees:  @DucTran999, @danielngo99

**Comment by danielngo99** [comment]
Test cases:
- [ ] Send a verification email for new registration.
- [ ] Resend a new email when the user clicks resend button.
- [ ] Use debounce to remove smashing on resend button.
- [ ] Only send unlock emails to the user already in the system.
- [ ] Fix submitting by hitting enter when the modal is opening.
- [ ] Prevent calling resend email API  by tools like Postman, thunder client, curl, etc.
